services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_ADDR: redis:6379
      REDIS_PASS: ""
    depends_on:
      - kafka
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
